// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: playground-oam/entities.proto

package grpc_playground_oam_go

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _entities_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on OAMMetadata with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *OAMMetadata) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Entries

	return nil
}

// OAMMetadataValidationError is the validation error returned by
// OAMMetadata.Validate if the designated constraints aren't met.
type OAMMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OAMMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OAMMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OAMMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OAMMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OAMMetadataValidationError) ErrorName() string { return "OAMMetadataValidationError" }

// Error satisfies the builtin error interface
func (e OAMMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOAMMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OAMMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OAMMetadataValidationError{}

// Validate checks the field values on OAMComponentSpec with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *OAMComponentSpec) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Type

	return nil
}

// OAMComponentSpecValidationError is the validation error returned by
// OAMComponentSpec.Validate if the designated constraints aren't met.
type OAMComponentSpecValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OAMComponentSpecValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OAMComponentSpecValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OAMComponentSpecValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OAMComponentSpecValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OAMComponentSpecValidationError) ErrorName() string { return "OAMComponentSpecValidationError" }

// Error satisfies the builtin error interface
func (e OAMComponentSpecValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOAMComponentSpec.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OAMComponentSpecValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OAMComponentSpecValidationError{}

// Validate checks the field values on OAMComponent with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *OAMComponent) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ApiVersion

	// no validation rules for Kind

	if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OAMComponentValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetSpec()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OAMComponentValidationError{
				field:  "Spec",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// OAMComponentValidationError is the validation error returned by
// OAMComponent.Validate if the designated constraints aren't met.
type OAMComponentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OAMComponentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OAMComponentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OAMComponentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OAMComponentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OAMComponentValidationError) ErrorName() string { return "OAMComponentValidationError" }

// Error satisfies the builtin error interface
func (e OAMComponentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOAMComponent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OAMComponentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OAMComponentValidationError{}
