// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: playground-oam/entities.proto

package grpc_playground_oam_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OAMMetadata with the metadata entries of an OAM component.
type OAMMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Entries associating key and value.
	Entries map[string]string `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *OAMMetadata) Reset() {
	*x = OAMMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_oam_entities_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OAMMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAMMetadata) ProtoMessage() {}

func (x *OAMMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_playground_oam_entities_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAMMetadata.ProtoReflect.Descriptor instead.
func (*OAMMetadata) Descriptor() ([]byte, []int) {
	return file_playground_oam_entities_proto_rawDescGZIP(), []int{0}
}

func (x *OAMMetadata) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

// OAMComponentSpec with the spec of an OAM component.
type OAMComponentSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Type of component
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *OAMComponentSpec) Reset() {
	*x = OAMComponentSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_oam_entities_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OAMComponentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAMComponentSpec) ProtoMessage() {}

func (x *OAMComponentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_playground_oam_entities_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAMComponentSpec.ProtoReflect.Descriptor instead.
func (*OAMComponentSpec) Descriptor() ([]byte, []int) {
	return file_playground_oam_entities_proto_rawDescGZIP(), []int{1}
}

func (x *OAMComponentSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// OAMComponent with the information of a component in the OAM spec.
type OAMComponent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ApiVersion of the component.
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Kind of component.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Metadata associated with the component.
	Metadata *OAMMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec associated with the component.
	Spec *OAMComponentSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *OAMComponent) Reset() {
	*x = OAMComponent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_oam_entities_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OAMComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAMComponent) ProtoMessage() {}

func (x *OAMComponent) ProtoReflect() protoreflect.Message {
	mi := &file_playground_oam_entities_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAMComponent.ProtoReflect.Descriptor instead.
func (*OAMComponent) Descriptor() ([]byte, []int) {
	return file_playground_oam_entities_proto_rawDescGZIP(), []int{2}
}

func (x *OAMComponent) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *OAMComponent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OAMComponent) GetMetadata() *OAMMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *OAMComponent) GetSpec() *OAMComponentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

var File_playground_oam_entities_proto protoreflect.FileDescriptor

var file_playground_oam_entities_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2d, 0x6f, 0x61, 0x6d,
	0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x6f, 0x61, 0x6d, 0x22,
	0x8d, 0x01, 0x0a, 0x0b, 0x4f, 0x41, 0x4d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x42, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x6f, 0x61,
	0x6d, 0x2e, 0x4f, 0x41, 0x4d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x26, 0x0a, 0x10, 0x4f, 0x41, 0x4d, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x53,
	0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xb2, 0x01, 0x0a, 0x0c, 0x4f, 0x41, 0x4d, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x69, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61,
	0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x37, 0x0a,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x6f, 0x61, 0x6d,
	0x2e, 0x4f, 0x41, 0x4d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x5f, 0x6f, 0x61, 0x6d, 0x2e, 0x4f, 0x41, 0x4d, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x42, 0x43, 0x5a, 0x41,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x70, 0x70, 0x74,
	0x69, 0x76, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x2d, 0x6f, 0x61, 0x6d, 0x2d, 0x67, 0x6f, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x6f, 0x61, 0x6d, 0x5f, 0x67,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_playground_oam_entities_proto_rawDescOnce sync.Once
	file_playground_oam_entities_proto_rawDescData = file_playground_oam_entities_proto_rawDesc
)

func file_playground_oam_entities_proto_rawDescGZIP() []byte {
	file_playground_oam_entities_proto_rawDescOnce.Do(func() {
		file_playground_oam_entities_proto_rawDescData = protoimpl.X.CompressGZIP(file_playground_oam_entities_proto_rawDescData)
	})
	return file_playground_oam_entities_proto_rawDescData
}

var file_playground_oam_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_playground_oam_entities_proto_goTypes = []interface{}{
	(*OAMMetadata)(nil),      // 0: playground_oam.OAMMetadata
	(*OAMComponentSpec)(nil), // 1: playground_oam.OAMComponentSpec
	(*OAMComponent)(nil),     // 2: playground_oam.OAMComponent
	nil,                      // 3: playground_oam.OAMMetadata.EntriesEntry
}
var file_playground_oam_entities_proto_depIdxs = []int32{
	3, // 0: playground_oam.OAMMetadata.entries:type_name -> playground_oam.OAMMetadata.EntriesEntry
	0, // 1: playground_oam.OAMComponent.metadata:type_name -> playground_oam.OAMMetadata
	1, // 2: playground_oam.OAMComponent.spec:type_name -> playground_oam.OAMComponentSpec
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_playground_oam_entities_proto_init() }
func file_playground_oam_entities_proto_init() {
	if File_playground_oam_entities_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_playground_oam_entities_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OAMMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playground_oam_entities_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OAMComponentSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playground_oam_entities_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OAMComponent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_playground_oam_entities_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playground_oam_entities_proto_goTypes,
		DependencyIndexes: file_playground_oam_entities_proto_depIdxs,
		MessageInfos:      file_playground_oam_entities_proto_msgTypes,
	}.Build()
	File_playground_oam_entities_proto = out.File
	file_playground_oam_entities_proto_rawDesc = nil
	file_playground_oam_entities_proto_goTypes = nil
	file_playground_oam_entities_proto_depIdxs = nil
}
